version: '3.1'
services:
  bookmedik:
    container_name: bookmedik
    image: ikerruiz/aplicacion_php:latest
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - 8082:80
    depends_on:
      - db

  db:
    container_name: servidor_mysql
    image: docker.io/library/mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
        - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
